export const SIGNAL_PATH = {
	ANSWER: 'ANSWER',
	ERROR: 'ERROR',
	ICE: 'ICE',
	JOIN: 'JOIN',
	LEAVE: 'LEAVE',
	OFFER: 'OFFER',
	TRACK: 'TRACK',
};

export const TOPIC_PATH = {
	CHAT: 'CHAT',
	DEVICE: 'DEVICE',
	EMOJI: 'EMOJI',
	HAND_UP: 'HANPUP',
	LEAVE: 'LEAVE',
	PARTICIPANT: 'PARTICIPANT',
};
