import type { Metadata } from 'next';

import './globals.css';
import RootProvider  from '@/provider/RootProvider';

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'MeetProject',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ko'>
			<body className='flex h-screen w-screen flex-col'>
				<RootProvider>
					<div id='alert' />
					<div id='modal' />
					<div id='feedback' />
					<div className='flex-1'>{children}</div>
				</RootProvider>
			</body>
		</html>
	);
}
